package com.example.matrix

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import androidx.recyclerview.widget.LinearLayoutManager
import com.example.matrix.databinding.ActivitySuccessBinding

class SuccessActivity : AppCompatActivity() {
    lateinit var binding: ActivitySuccessBinding

    private val dataSuccess = listOf(
        DataModel("یاد بگیر...(1)"),
        DataModel("یاد بگیر...(2)"),
        DataModel("یاد بگیر...(3)"),
        DataModel("یاد بگیر...(4)"),
        DataModel("یاد بگیر...(5)"),
        DataModel("یاد بگیر...(6)"),
        DataModel("یاد بگیر...(7)"),
        DataModel("یاد بگیر...(8)"),
        DataModel("یاد بگیر...(9)"),
        DataModel("یاد بگیر...(10)"),
        DataModel("یاد بگیر...(11)"),
        DataModel("یاد بگیر...(12)"),
        DataModel("یاد بگیر...(13)"),
        DataModel("یاد بگیر...(14)"),
        DataModel("یاد بگیر...(15)"),
        DataModel("یاد بگیر...(16)"),
        DataModel("یاد بگیر...(17)"),
        DataModel("یاد بگیر...(18)"),
        DataModel("یاد بگیر...(19)"),
        DataModel("یاد بگیر...(20)"),
        DataModel("یاد بگیر...(21)"),
        DataModel("یاد بگیر...(22)"),
        DataModel("یاد بگیر...(23)"),
        DataModel("یاد بگیر...(24)"),
        DataModel("یاد بگیر...(25)"),
        DataModel("یاد بگیر...(26)"),
        DataModel("یاد بگیر...(27)"),
        DataModel("یاد بگیر...(28)"),
        DataModel("یاد بگیر...(29)"),
        DataModel("یاد بگیر...(30)"),
        DataModel("یاد بگیر...(31)"),
        DataModel("یاد بگیر...(32)"),
        DataModel("1- قانون علت و معلول"),
        DataModel("2- قانون ذهن"),
        DataModel("3- قانون عینیت یافتن ذهنیات"),
        DataModel("4- قانون رابطه ی مستقیم"),
        DataModel("5- قانون باور"),
        DataModel("6- قانون ارزش ها"),
        DataModel("7- قانون انگیزه"),
        DataModel("8- قانون فعالیت ذهن ناخودآگاه"),
        DataModel("9- قانون انتظارات"),
        DataModel("10- قانون تمرکز"),
        DataModel("11- قانون عادت"),
        DataModel("12- قانون جذب"),
        DataModel("13- قانون انتخاب"),
        DataModel("14- قانون تفکر مثبت"),
        DataModel("15- قانون تغییر"),
        DataModel("16- قانون کنترل"),
        DataModel("17- قانون مسئولیت"),
        DataModel("18- قانون پاداش"),
        DataModel("19- قانون خدمت"),
        DataModel("20- قانون تاثیر تلاش"),
        DataModel("21- قانون آمادگی"),
        DataModel("22- قانون حد توانایی"),
        DataModel("23- قانون تصمیم"),
        DataModel("24- قانون خلاقیت"),
        DataModel("25- قانون انعطاف پذیری"),
        DataModel("26- قانون استقامت"),
        DataModel("27- قانون صداقت"),
        DataModel("28- قانون احساس"),
        DataModel("29- قانون خوشبختی"),
        DataModel("30- قانون جایگزینی"),
        DataModel("31- قانون اظهار"),
        DataModel("32- قانون عکس العمل"),
        DataModel("33-  قانون تجسم"),
        DataModel("34- قانون تمرین"),
        DataModel("35- قانون تعهد"),
        DataModel("36- قانون ارزش"),
        DataModel("37- قانون تفاهم"),
        DataModel("38- قانون ارتباطات"),
        DataModel("39- قانون توجه"),
        DataModel("40- قانون عزت نفس"),
        DataModel("41- قانون تلاش غیرمستقیم"),
        DataModel("42- قانون تلاش معکوس"),
        DataModel("43- قانون هویت"),
        DataModel("44- قانون بخشش"),
        DataModel("45- قانون پذیرش واقعیت"),
        DataModel("46- قانون کم کوشی"),
        DataModel("47- قانون حداکثر"),
        DataModel("48- قانون مصلحت"),
        DataModel("49- قانون دوگانگی"),
        DataModel("50- قانون انتخاب"),
        DataModel("51- قانون ارزش واقعی"),
        DataModel("52- قانون تعجیل"),
        DataModel("53- قانون ارزش نهایی"),
        DataModel("54- قانون عرضه و تقاضا"),
        DataModel("55- قانون کهن (Kohen)"),
        DataModel("56- قانون داوسن (Davson)"),
        DataModel("57- قانون تعیین مهلت"),
        DataModel("58- قانون شرایط پرداخت"),
        DataModel("59- قانون آمادگی"),
        DataModel("60- قانون جابجایی"),
        DataModel("61- قانون اشتیاق"),
        DataModel("62- قانون عمل متقابل"),
        DataModel("63- قانون عدم ختم معامله"),
        DataModel("64- قانون وفور نعمت"),
        DataModel("65- قانون معاوضه"),
        DataModel("66- قانون سرمایه"),
        DataModel("67- قانون پس انداز"),
        DataModel("68- قانون نگهداری"),
        DataModel("69- قانون پارکینسون"),
        DataModel("70- قانون سرمایه گذاری"),
        DataModel("71- قانون بهره ی مرکب"),
        DataModel("72- قانون برآیند"),
        DataModel("73- قانون جذب"),
        DataModel("74- قانون اشتیاق"),
        DataModel("75- قانون هدف"),
        DataModel("76- قانون ثروتمند کردن"),
        DataModel("77- قانون کارآفرینی"),
        DataModel("78- قانون خودساختگی"),
        DataModel("79- قانون آمادگی برای شکست"),
        DataModel("80- قانون ریسک"),
        DataModel("81- قانون خوش بینی نابجا"),
        DataModel("82- قانون ثبات قدم"),
        DataModel("83- قانون هدف تجارت"),
        DataModel("84- قانون سازمان"),
        DataModel("85- قانون رضایت مشتری"),
        DataModel("86- قانون مشتری"),
        DataModel("87- قانون کیفیت"),
        DataModel("88- قانون کهنگی"),
        DataModel("89- قانون ابتکار"),
        DataModel("90- قانون عوامل ضروری موفقیت"),
        DataModel("91- قانون بازار"),
        DataModel("92- قانون تخصصی کردن"),
        DataModel("93- قانون تمایز"),
        DataModel("94- قانون تعیین خریدار"),
        DataModel("95- قانون تمرکز بازار"),
        DataModel("96- قانون برتری"),
        DataModel("97- قانون احتمالات"),
        DataModel("98- قانون وضوح اهداف"),
        DataModel("99- قانون جذب"),
        DataModel("100- قانون توقعات"),
        DataModel("101- قانون فرصت"),
        DataModel("102- قانون قابلیت"),
        DataModel("103- قانون دانش"),
        DataModel("104- قانون پیش فرض ها"),
        DataModel("105- قانون وقت شناسی"),
        DataModel("106- قانون انرژی"),
        DataModel("107- قانون روابط"),
        DataModel("108- قانون درک دیگران"),
        DataModel("109- قانون رشد"),
        DataModel("110- قانون تکرار"),
        DataModel("111- قانون پشتکار"),
        DataModel("112- قانون خودشکوفایی"),
        DataModel("113- قانون استعدادها"),
        DataModel("114- قانون کمال"),
        DataModel("115- قانون موقعیت"),
        DataModel("116- قانون شهامت"),
        DataModel("117- قانون سخت کوشی"),
        DataModel("118- قانون بخشندگی"),
        DataModel("119- قانون پذیرش"),
        DataModel("120- قانون خوش بینی"),
        DataModel("منبع")
    )

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivitySuccessBinding.inflate(layoutInflater)
        setContentView(binding.root)

        binding.recyclerViewSuccess.layoutManager = LinearLayoutManager(this)
        val adapterSuccess = RecyclerSuccessAdapter(dataSuccess,this)
        binding.recyclerViewSuccess.adapter = adapterSuccess

    }
}